Add ipmi device for pmon container (#24037)
Why I did it
On platforms using the IPMI interface, the current pmon is broken.

root@sonic:~# show logging "Could not open device"
2025 Sep 18 02:18:30.578482 sonic INFO pmon#supervisord: psud Could not open device at /dev/ipmi0 or /dev/ipmi/0 or /dev/ipmidev/0: No such file or directory
2025 Sep 18 02:18:31.689267 sonic INFO pmon#supervisord: psud Could not open device at /dev/ipmi0 or /dev/ipmi/0 or /dev/ipmidev/0: No such file or directory
2025 Sep 18 02:21:55.434346 sonic INFO pmon#supervisord: psud Could not open device at /dev/ipmi0 or /dev/ipmi/0 or /dev/ipmidev/0: No such file or directory
2025 Sep 18 02:21:57.355865 sonic INFO pmon#supervisord: psud Could not open device at /dev/ipmi0 or /dev/ipmi/0 or /dev/ipmidev/0: No such file or directory
2025 Sep 18 02:21:57.355865 sonic INFO pmon#supervisord: thermalctld Could not open device at /dev/ipmi0 or /dev/ipmi/0 or /dev/ipmidev/0: No such file or directory
2025 Sep 18 02:21:58.653110 sonic INFO pmon#supervisord: psud Could not open device at /dev/ipmi0 or /dev/ipmi/0 or /dev/ipmidev/0: No such file or directory
root@sonic:~# docker exec -it pmon bash -c "ls /dev/ipmi*"
ls: cannot access '/dev/ipmi*': No such file or directory
root@sonic:~# show platform psustatus
Error: Failed to get PSU status
Error: failed to get PSU status from state DB
root@sonic:~# show platform temperature
Thermal Not detected
root@sonic:~#
After this fix

root@sonic:~# show logging "Could not open device"
root@sonic:~# docker exec -it pmon bash -c "ls /dev/ipmi*"
/dev/ipmi0
root@sonic:~# show platform psustatus
PSU    Model       Serial               HW Rev      Voltage (V)    Current (A)    Power (W)  Status    LED
-----  ----------  -------------------  --------  -------------  -------------  -----------  --------  -----
PSU1   YNEE0750EM  F7510AS90580X020027  N/A                0.00           0.00         0.00  NOT OK    green
PSU2   YNEE0750EM  F7510AS90580X020024  N/A               12.12          10.00       121.20  OK        green
root@sonic:~# show platform temperature
          Sensor    Temperature    High TH    Low TH    Crit High TH    Crit Low TH    Warning          Timestamp
----------------  -------------  ---------  --------  --------------  -------------  ---------  -----------------
      PSU1_TEMP1             32        N/A       N/A             N/A            N/A      False  20250918 02:07:24
      PSU2_TEMP1             32        N/A       N/A             N/A            N/A      False  20250918 02:07:24
    TEMP_ENV_BMC             37       75.0       N/A            80.0            N/A      False  20250918 02:07:23
TEMP_ENV_MACCASE             40       75.0       N/A            80.0            N/A      False  20250918 02:07:23
TEMP_ENV_PSUCASE             32       57.0       N/A            62.0            N/A      False  20250918 02:07:23
TEMP_ENV_SSDCASE             42       75.0       N/A            80.0            N/A      False  20250918 02:07:23
        TEMP_MAC             41       95.0       N/A           105.0            N/A      False  20250918 02:07:22
 TEMP_PSU0_TEMP1             32        N/A       N/A            70.0            N/A      False  20250918 02:07:23
 TEMP_PSU1_TEMP1             32        N/A       N/A            70.0            N/A      False  20250918 02:07:24
root@sonic:~#
This regression was introduced by #23457

Signed-off-by: Feng Pan <fenpan@microsoft.com>