Merged PR 7547826: Exception does not have attribute 'reason'
CA_cert_downloader.py has new crash issue, and the root cause is Exception does not have attribute 'reason'

1. How to verify

I use kvm environment to verify:
Modify CA_cert_downloader.py to raise Expection and OSError, and restart CA_cert_downloader.
Check syslog, and CA_cert_downloader does not crash.

2. Call stack

Jan 19 08:49:55.933049 AMS08-0101-0811-02M0 INFO acms#CA_cert_downloader.py: CA_cert_downloader: get_cert: URL: https://ussouth-dsms.dsms.core.windows.net/dsms/issuercertificates?getissuersv3&caname=ame

Jan 19 08:49:56.248149 AMS08-0101-0811-02M0 ERR acms#CA_cert_downloader.py: CA_cert_downloader: get_cert: Unable to reach https://ussouth-dsms.dsms.core.windows.net/dsms/issuercertificates?getissuersv3&caname=ame

Jan 19 08:49:56.249408 AMS08-0101-0811-02M0 INFO acms#/supervisord: CA_cert_downloader Traceback (most recent call last):

Jan 19 08:49:56.249998 AMS08-0101-0811-02M0 INFO acms#/supervisord: CA_cert_downloader   File "/usr/bin/CA_cert_downloader.py", line 92, in <module>

Jan 19 08:49:56.250563 AMS08-0101-0811-02M0 INFO acms#/supervisord: CA_cert_downloader     main()

Jan 19 08:49:56.251162 AMS08-0101-0811-02M0 INFO acms#/supervisord: CA_cert_downloader   File "/usr/bin/CA_cert_downloader.py", line 81, in main

Jan 19 08:49:56.251686 AMS08-0101-0811-02M0 INFO acms#/supervisord: CA_cert_downloader     if get_cert(CERTIFICATE_AUTHORITY, API_URL):

Jan 19 08:49:56.252166 AMS08-0101-0811-02M0 INFO acms#/supervisord: CA_cert_downloader   File "/usr/bin/CA_cert_downloader.py", line 73, in get_cert

**Jan 19 08:49:56.252629 AMS08-0101-0811-02M0 INFO acms#/supervisord: CA_cert_downloader     sonic_logger.log_error("CA_cert_downloader: get_cert: "+str(e.reason))**

**Jan 19 08:49:56.253089 AMS08-0101-0811-02M0 INFO acms#/supervisord: CA_cert_downloader AttributeError: 'error' object has no attribute 'reason'**

Jan 19 08:49:57.349116 AMS08-0101-0811-02M0 INFO acms#/supervisor-proc-exit-listener: Process 'CA_cert_downloader' exited unexpectedly. Terminating supervisor 'acms'

Jan 19 08:50:35.970999 AMS08-0101-0811-02M0 INFO acms#supervisord 2023-01-19 08:49:56,264 INFO exited: CA_cert_downloader (exit status 1; not expected)

Jan 19 08:50:35.971160 AMS08-0101-0811-02M0 INFO acms#supervisord 2023-01-19 08:49:57,269 INFO spawned: 'CA_cert_downloader' with pid 18834

Jan 19 08:50:35.971698 AMS08-0101-0811-02M0 INFO acms#supervisord 2023-01-19 08:49:57,350 INFO success: CA_cert_downloader entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)

Jan 19 08:50:35.972259 AMS08-0101-0811-02M0 INFO acms#supervisord 2023-01-19 08:49:57,353 INFO waiting for supervisor-proc-exit-listener, start, rsyslogd, CA_cert_downloader, cert_converter to die

Jan 19 08:50:35.972811 AMS08-0101-0811-02M0 INFO acms#supervisord 2023-01-19 08:49:59,362 INFO stopped: CA_cert_downloader (terminated by SIGTERM)

Jan 19 08:50:35.981131 AMS08-0101-0811-02M0 INFO acms#supervisord 2023-01-19 08:50:34,934 INFO spawned: 'CA_cert_downloader' with ...