[test] Bump sonic-swss-common to 4575804 (rebased onto upstream master)
Rebase feature/component-stats onto upstream/master to pick up
ZmqProducerBatchedSet/ZmqProducerBatchedDel SWIG bindings (PR #1188)
required by sonic-gnmi master, fixing the build failure:

  sonic_data_client/mixed_db_client.go:315:13:
    undefined: swsscommon.ZmqProducerBatchedSet
  sonic_data_client/mixed_db_client.go:321:13:
    undefined: swsscommon.ZmqProducerBatchedDel

Signed-off-by: Yutong Zhang <yutongzhang@microsoft.com>