Add es-1227-36ts-p install, postinst file [Error Log] admin@sonic:~$ show platform firmware status Traceback (most recent call last):   File "/usr/local/lib/python3.11/dist-packages/fwutil/__init__.py", line 2, in <module>     from sonic_platform.platform import Platform ModuleNotFoundError: No module named 'sonic_platform'
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/fwutil", line 5, in <module>
    from fwutil.main import cli
  File "/usr/local/lib/python3.11/dist-packages/fwutil/__init__.py", line 5, in <module>
    raise ImportError("Required module not found: {}".format(str(e)))
ImportError: Required module not found: No module named 'sonic_platform'

[Test Log]
admin@sonic:~$ show platform firmware status
Chassis                Module    Component     Version                Description
---------------------  --------  ------------  ---------------------  ---------------------------------------
wistron_es1227_36ts_p  N/A       U-Boot        2023.01-12.25.111.3.0  Performs initialization during booting
                                 ONIE-VERSION  v0.1                   ONIE - Open Network Install Environment
                                 CPLD          2.1.0                  CPLD firmware
                                 PoE           3.5                    Power over Ethernet controller firmware
 Changes to be committed:
	new file:   platform/marvell-prestera/sonic-platform-wistron/debian/sonic-platform-es1227-36ts-p.install
	new file:   platform/marvell-prestera/sonic-platform-wistron/debian/sonic-platform-es1227-36ts-p.postinst