Fixed interfaces-config.service failure on chassis during first boot if there is no config present
<!--
     Please make sure you've read and understood our contributing guidelines:
     https://github.com/Azure/SONiC/blob/gh-pages/CONTRIBUTING.md

     ** Make sure all your commits include a signature generated with `git commit -s` **

     If this is a bug fix, make sure your description includes "fixes #xxxx", or
     "closes #xxxx" or "resolves #xxxx"

     Please provide the following information:
-->

#### Why I did it
Fixes https://github.com/sonic-net/sonic-buildimage/issues/22947

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it
Added check for DEVCIE_METADATA before using it.

#### How to verify it
1. Sonic-installer install a system without any config migration.
2. Just to validate the file:
sonic-cfggen -t /usr/share/sonic/templates/interfaces.j2

Without change:
```
sonic-cfggen -t /usr/share/sonic/templates/interfaces.j2
Traceback (most recent call last):
  File "/usr/local/bin/sonic-cfggen", line 517, in <module>
    main()
  File "/usr/local/bin/sonic-cfggen", line 481, in main
    template_data = template.render(data)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/share/sonic/templates/interfaces.j2", line 31, in top-level template code
    {% block mgmt_interface %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/sonic/templates/interfaces.j2", line 134, in block 'mgmt_interface'
    {% if not (DEVICE_METADATA['localhost']['subtype'] == 'SmartSwitch' and DEVICE_METADATA['localhost']['switch_type'] == 'dpu') %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 466, in getitem
    return obj[argument]
           ~~~^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'DEVICE_METADATA' is undefined
```

With change:
```
#
# =============== Managed by SONiC Config Engine DO NOT EDIT! ===============
# generated from /usr/share/sonic/templates/interfaces.j2 using sonic-cfggen
# file: /etc/network/interfaces
#
# The loopback network interface
auto lo
iface lo inet loopback
   address 127.0.0.1
   netmask 255.255.0.0
   scope host
   post-up ip addr del 127.0.0.1/8 dev lo
   pre-down ip addr add 127.0.0.1/8 dev lo

# The management network interface
auto eth0
iface eth0 inet dhcp
    metric 202
iface eth0 inet6 dhcp
    up sysctl net.ipv6.conf.eth0.accept_ra=1
    down sysctl net.ipv6.conf.eth0.accept_ra=0
#
source /etc/network/interfaces.d/*
#
```
<!--
If PR needs to be backported, then the PR must be tested against the base branch and the earliest backport release branch and provide tested image version on these two branches. For example, if the PR is requested for master, 202211 and 202012, then the requester needs to provide test results on master and 202012.
-->

#### Which release branch to backport (provide reason below if selected)

<!--
- Note we only backport fixes to a release branch, *not* features!
- Please also provide a reason for the backporting below.
- e.g.
- [x] 202006
-->

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211
- [ ] 202305
- [x] 202505

#### Tested branch (Please provide the tested image version)

<!--
- Please provide tested image version
- e.g.
- [x] 20201231.100
-->

- [ ] <!-- image version 1 -->
- [ ] <!-- image version 2 -->

#### Description for the changelog
<!--
Write a short (one line) summary that describes the changes in this
pull request for inclusion in the changelog:
-->

<!--
 Ensure to add label/tag for the feature raised. example - PR#2174 under sonic-utilities repo. where, Generic Config and Update feature has been labelled as GCU.
-->

#### Link to config_db schema for YANG module changes
<!--
Provide a link to config_db schema for the table for which YANG model
is defined
Link should point to correct section on https://github.com/Azure/sonic-buildimage/blob/master/src/sonic-yang-models/doc/Configuration.md
-->

#### A picture of a cute animal (not mandatory but encouraged)