[sonic-device-data] Add execute permission to platform_asic_checker test script
Fix build failure caused by missing execute permission.
The platform_asic_checker script is executed during build but had
644 permissions instead of 755.

Error: /bin/bash: line 15: ./platform_asic_checker: Permission denied
Signed-off-by: Liping Xu <xuliping@microsoft.com>