[ast2700-bmc] Wire pldm_errors.annotate() into ComponentBMC._format_error()
Annotates pldm-fw stderr with DSP0267 spec descriptions when logging
firmware update errors.  Before this change, an error like:

  CalledProcessError: ... 0x84

would appear as-is.  After:

  CalledProcessError: ... 0x84 (INVALID_STATE_FOR_COMMAND: The FD/FDP
  is not in a state to expect this command)

Related: https://redmine.mellanox.com/issues/5221533

Signed-off-by: Brian Carr <brcarr@nvidia.com>